# name: Playwright_Prod_Tests

# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         description: "Name of the calling workflow"
#         required: true
#         default: "Self"

# env:
#   HOME: /root

# jobs:
#   test:
#     uses: ./.github/workflows/playwright-reusable.yml
#     with:
#       environment: https://www.northerntrust.com
#     secrets: inherit
